version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
        - "$PWD/db_data:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - 80:80
     restart: always
     volumes:
        - "$PWD/wp-content:/var/www/html"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   wpcli:
     image: wordpress:cli
     volumes:
       - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
       - ./wp-app:/var/www/html
     depends_on:
       - db
       - wordpress
